/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "collaborator_constants.h"

namespace huang { namespace collaborator {

const collaboratorConstants g_collaborator_constants;

collaboratorConstants::collaboratorConstants() {
}

}} // namespace

