/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef collaborator_CONSTANTS_H
#define collaborator_CONSTANTS_H

#include "collaborator_types.h"

namespace huang { namespace collaborator {

class collaboratorConstants {
 public:
  collaboratorConstants();

};

extern const collaboratorConstants g_collaborator_constants;

}} // namespace

#endif
